# based on https://github.com/jurplel/install-qt-action/blob/master/.github/workflows/test.yml

name: Build and Deploy

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]

jobs:
  windows-build:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v2
      - name: Cache Qt
        id: cache-qt
        uses: actions/cache@v2
        with:
          path: ../Qt
          key: windows-QtCache
      - name: Install Qt with options
        uses: jurplel/install-qt-action@v2
        with:
          modules: 'qtwebengine'
          version: 5.15.1
          tools: 'tools_ifw,4.0,qt.tools.ifw.40'
          cached: ${{ steps.cache-qt.outputs.cache-hit }}
      - name: Configure
        run: |
          call "%programfiles(x86)%\Microsoft Visual Studio\2019\Enterprise\VC\Auxiliary\Build\vcvars64.bat"
          dir %Qt5_DIR%/lib/cmake
          choco install jom -y
          choco install openssl -y
          qmake "CONFIG+=release"
          jom
        shell: cmd
  ubuntu-build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Cache Qt
        id: cache-qt
        uses: actions/cache@v2
        with:
          path: ../Qt
          key: ubuntu-QtCache
      - name: Install Qt with options
        uses: jurplel/install-qt-action@v2
        with:
          modules: 'qtwebengine'
          version: 5.15.1
          tools: 'tools_ifw,4.0,qt.tools.ifw.40'
          cached: ${{ steps.cache-qt.outputs.cache-hit }}
      - name: Configure
        run: |
          ls $Qt5_DIR/lib/cmake
          qmake CONFIG+=release
          make
        shell: bash
